name: check

on: 
  push:
    branches:
    - only-cmake-js
  pull_request:
    branches:
    - only-cmake-js

jobs:
  test:
    name: test
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        node: [12, 14, 16]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      timeout-minutes: 1
      with:
        node-version: ${{ matrix.node }}
    - name: install
      run: npm install
    - name: test
      run: npm run test
